title: Abhishek Kumar Goyal
logo: /assets/img/profile.png
description: 
  <br>
  I'm a Lead Software Engineer working in a service-based organization with an experience of 5 years. I'm interested in ML and AI and look to learn more about it and consequently work in this field. 
  <br>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
